### ISSUE TITLE
Versioning of output css

### ISSUE THREAD

**Issue by Tajdik** [sepiariver/cssSweet#11]
Hi,
when I am making changes in CSS files, I often cant see changes immediately (css is in browser cache). It has relatively simple solution - adding parameters to css file. 
For example `style.css?modified=20150620`.
But right now there is no solution to do that. Can you please add this functionality to your great Extra?
Now I am using parameters with snippet, which outputs actual time. But just for development.

**Comment by adamwintle** [comment]
I would recommend adding the timestamp or hash into the filename itself, e.g. `style.20150620.css`, so the file is always truly unique. This is become some CDN proxies don't consider `?` as unique, and can sometimes ignore anything after the `?`, which results in the files remaining cached until manually purged. 

This can be fixed by configuring the CDN properly, some cheaper CDNs have this problem. Only up until recently CloudFront always ignored stuff after `?`, but now it's configurable. 

This alternative solution to cssSweet adds the hash to the file names automatically: https://github.com/bezumkin/MinifyX

**Comment by sepiariver** [comment]
The intention was to increment a system setting, because a date may not be granular enough. Of course a Unix timestamp could be used, or a unique hash of timestamp + user ID, but I'm not sure how much value that would add to real-life situations.

The advantage of using a system setting, I thought, is that you could call it into your template easily without the overhead of an additional plugin to populate some placeholder or register the CSS file on every request. It would look like this:

`<link rel="stylesheet" href="path/to/css/custom.min.css?any-param-key=[[++csss.vers]]">`

You would have the freedom to use whatever URL parameter you want, and you can configure your CDN to recognize or ignore those. There would also be an option to modify the filename:

`<link rel="stylesheet" href="path/to/css/custom.min.[[++csss.vers]].css">`

In this case you would enable a plugin setting to "append cssSweet version ID to filename". Also, with the value accessible via a System Setting, you could override it manually.

Thoughts? 
@adamwintle @Tajdik 
P.S. I've targeted this for version 2.1

**Comment by Tajdik** [comment]
I like both ideas, but "filename way" bit more. Im looking forward to see new version of cssSweet. Its really great Extra. Thanks.

**Comment by sepiariver** [comment]
It's in the works https://github.com/sepiariver/cssSweet/commit/7303d45ab3f676c42340444920393d877556b6ff

**Comment by sepiariver** [comment]
The incremental version is going to be the first iteration, because I can turn it into an integer and increment it. Eventually I'll consider hashing it, but I'd have to store the hash somewhere, in a custom table, in order to make it available as a placeholder in the Template. If I put a hash in a system setting I can't do much in the way of checking: I always have to overwrite it, and the filenames won't have much information about which was the latest.

I dunno...thoughts about uniqueness of generated filename, and the benefits of using incremental version?

@adamwintle @Tajdik

**Comment by Tajdik** [comment]
I wrote simple snippet to get time of last change of css file.
```php
<?php
$filename = 'path/to/style.css';
if (file_exists($filename)) {
    $output = date("His", filemtime($filename)); // Time of change in time format - 235959
}
return $output;
```
and using it in template:
```html
<link rel="stylesheet" href="path-to/style.css?v-[[!time-of-change]]">
```
And this works also, if you dont want use "?".
```html
<link rel="stylesheet" href="path-to/style.css#[[!time-of-change]]">
```
Its simple and get work done :-) And I don't have to worry, when i forgot to change template on production website.

**Comment by sepiariver** [comment]
@Tajdik if you're really only after cache-busting, I think this is the way to go. What I've done so far on the "versioning" feature is a bit crude, at best. I don't want it to hold up getting some of the other, more important features tested and packaged (like the updated scssphp library)

I'm gonna revert the work I've done on this so far, based on your feedback, and close this issue. In a future version, I may try to architect a more robust "real" versioning feature, but it will take some time to do it right.

**Comment by Tajdik** [comment]
Yes, this works for me, so have no problem with closing this issue. It'd rather when development will focus on updated scssphp library, and so on. Thank you for your work.
