### ISSUE TITLE
Syntax highlighting?

### ISSUE THREAD

**Issue by Boddlnagg** [sepiariver/cssSweet#15]
I have installed Ace in my MODX installation, and it supports syntax highlighting for (S)CSS when editing such a file directly in the "Files" tab. This doesn't work if the stylesheet is edited as a chunk, however, since chunks are always considered to be HTML (by Ace). So maybe you could find a way to enabled syntax highlighting when editing the SCSS files that I use with cssSweet. Two ideas (don't know either of these is possible):
- Find a way to have Ace recognize/highlight certain chunks as SCSS files.
- Compile the stylesheets when editing/saving from the "Files" tab, without the need for a chunk (my stylesheet chunks are backed by static files anyway).

**Comment by sepiariver** [comment]
Ace is supposed to support correct syntax highlighting if the Chunk uses a static file with a recognized extension. In version 1.5.1 of Ace this worked perfectly, but since then it hasn't. I'll create an issue there, maybe you can help make it a priority by commenting on it?

In the meantime I'll see if I can fire cssSweet on the File Save event.

**Comment by Boddlnagg** [comment]
I see, this has already been reported [in the MODX forum](http://forums.modx.com/thread/81257/ace-code-editor-for-modx-revolution---support-thread?page=6#dis-post-530764).
