### ISSUE TITLE
Question: How does it work with multiple contexts?

### ISSUE THREAD

**Issue by sonicpunk** [sepiariver/cssSweet#18]
In my project, the admin needs to have multiple sites via contexts in the Manager.  I am using the same templates for each context, and the admin can change colors of the theme.  My plan was to use color picker TVs and have then assigned to a color_setup template or something of that nature, so that each context has its own color scheme.  

How would I best use cssSweet to accomplish this?  I read that there are general system settings for things like filename, path, etc.  In my case I need these settings to be either context settings or TVs.

I was also planning on using the content area of the resource for my css code.

Is there documentation for this?  Is this a problem?

**Comment by sepiariver** [comment]
The latest version 3.x supports context settings, but currently the Plugin can only output different files (have different settings) via different Property sets. So you would enable property set A for context A, then change the Plugin to fire with property set B for context B...etc. It's not ideal.

The "dev mode" feature was a stepping-stone to true, multi-context support. So that's coming in a future version. Possibly sooner than later, since you are not the first person to ask about it ;)
