### ISSUE TITLE
Since MODX 2.8.3 stopped working

### ISSUE THREAD

**Issue by crimsonpixel** [sepiariver/cssSweet#31]
I have had the cssSweet working fine till I upgraded to MODX 2.8.3 and whilst it says in the logs that the plugin is running, it doesn't appear to be updating the output.

Not errors in the error log.

Running on PHP 7.4

**Comment by sepiariver** [comment]
Looking into this

**Comment by sepiariver** [comment]
Unfortunately I was not able to reproduce this. I think most likely it has to do with the type of the dev_mode plug-in property. 

Please try changing it to a string like `custom` rather than a Boolean field. You can’t do this by right-clicking the property in the Plugin’s property edit view and choosing “Update Property”

Also check that the path to which the output files are being saved matches what you expect and are included in your front end as such

Let me know how it goes @crimsonpixel

**Comment by crimsonpixel** [comment]
Found the issue - the css_path was set to assets/theme/css  when it should have been [[++assets_path]]theme/css/

All works correctly now.
