### ISSUE TITLE
Plugin not in category

### ISSUE THREAD

**Issue by sottwell** [sepiariver/cssSweet#7]
On installing, the saveCustomCSS plugin is not installed in the cssSweet category.

**Comment by sepiariver** [comment]
@sottwell I think this is fixed in version 1.2.1-pl

Please let me know if this is not the case. You may or may not be installing this Extra from the Repo anymore, as I know you have your own special sauce going on.

BTW, did you share your version of the plugin code or is it in a PR? I'm going to incorporate it into version 2.0.0 coming before the end of April, if all goes well.

Thank you!
