### ISSUE TITLE
csss.custom_css_chunk setting does not work

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [sepiariver/cssSweet#9]
I changed the csss.custom_css_chunk name to solo.custom.css
And csss.custom_css_filename to solo-custom.css
Also the csss.custom_css_path is set to: {assets_path}components/solo/

The plugin keeps using the default names and is not using the path.

    Console running...
    [pThumb Cache Manager] Clean Level: 0 || Max Age: 30 days || Max Size: 100 MB || Max Files: 10000
    :: Skipping cache cleanup based on settings
    
    csss.custom_css_path was not defined. Path set to /home/solodevmpthemes/public_html/assets/components/csssweet/
    Success! Custom CSS saved to file "/home/solodevmpthemes/public_html/assets/components/csssweet/csss-custom.css"
    Processing automatic publishing dates
    -> 0 documents were published.
    -> 0 documents were unpublished.
    Regenerating system settings cache: Refresh successful!
    Regenerating the context caches
    -> mgr: Refresh successful!
    -> web: Refresh successful!

![screen](https://cloud.githubusercontent.com/assets/725851/6927459/de19fa0c-d7ed-11e4-8021-f83cb1559a0f.jpg)

**Comment by sepiariver** [comment]
@DESIGNfromWITHIN This has been confirmed, however it *should* work. For some reason the `$modx->getOption()` method isn't using the system setting as a default. 

Can you confirm please if it's working when you put the path in the plugin properties?

**Comment by DESIGNfromWITHIN** [comment]
Will do tomorrow, going to bed now...
Op 31 mrt. 2015 22:28 schreef "Sepia River" <notifications@github.com>:

**Comment by DESIGNfromWITHIN** [comment]
I tried and all looks like it is working but no css file is created...

![screen-1](https://cloud.githubusercontent.com/assets/725851/6937909/8341ebfe-d85f-11e4-8b55-96665425f8dd.jpg)
![screen-2](https://cloud.githubusercontent.com/assets/725851/6937910/83535ff6-d85f-11e4-9654-05d0aa9908d9.jpg)
![screen-3](https://cloud.githubusercontent.com/assets/725851/6937911/8364438e-d85f-11e4-998d-24612975a423.jpg)

**Comment by DESIGNfromWITHIN** [comment]
I even tried hardcoding my own path to the plugin still no go...

**Comment by sepiariver** [comment]
Menno would you be willing to provide a login for me to troubleshoot cssSweet in your site please?

YJ Tso

Pecked on a tiny keyboard.

**Comment by sepiariver** [comment]
Ok @DESIGNfromWITHIN my bad. In my instructions previously I'd said to use the `{assets_path}` syntax but that's not available in Plugin properties. You must use `[[++assets_path]]`

Note: it's "assets" NOT "asset" because I noticed a typo in there before I started messing around ;)

Additionally, you MUST enable processing of tags in properties, in the Plugin properties tab. See screenshot please: 
![screenshot 2015-04-01 10 26 32](https://cloud.githubusercontent.com/assets/821671/6947110/dc9fdd42-d859-11e4-9cb4-515ce7867b23.png)

This worked. I tested it several times, after pasting in the default plugin code.

In the next major version, I'm actually going to remove the references to system_settings, because the nested `$modx->getOption()` calls aren't working and we've yet to figure out why. But anyways those settings belong in properties rather than system settings, because then you can apply different property sets to different events.

Another note: the "OnChunkFormSave" property is NOT enabled by default. I didn't want unexpected behaviour for those who are upgrading. In the next major version it will be enabled by default. It's very useful when editing CSS Chunks, because as soon as you save, as long as the Chunk is in the list of Chunks to process, the concatenated file will be written.

Let me know if it continues to work ok for you, as I've tested, or if you run into any other problems :smile:
